# Generated by Django 5.2.1 on 2025-05-28 23:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_passwordsetuptoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordsetuptoken',
            options={'ordering': ['-created_at'], 'verbose_name': 'Token de Contraseña', 'verbose_name_plural': 'Tokens de Contraseña'},
        ),
        migrations.AlterModelOptions(
            name='usersettings',
            options={'verbose_name': 'Configuración de Usuario', 'verbose_name_plural': 'Configuraciones de Usuario'},
        ),
        migrations.AlterField(
            model_name='passwordsetuptoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='core_settings', to=settings.AUTH_USER_MODEL),
        ),
    ]
