# Generated by Django 5.2.1 on 2025-06-22 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='email_notifications',
            field=models.BooleanField(default=True, verbose_name='Notificaciones por Email'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='task_reminders',
            field=models.BooleanField(default=False, verbose_name='Recordatorio de Tareas'),
        ),
    ]
