# Generated by Django 5.2.1 on 2025-06-26 05:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('target_datetime', models.DateTimeField()),
                ('reminder_type', models.CharField(choices=[('email', 'Email'), ('calendar', 'Calendario'), ('both', 'Ambos')], default='email', max_length=10)),
                ('timing', models.CharField(choices=[('immediate', 'Inmediato'), ('5min', '5 minutos antes'), ('15min', '15 minutos antes'), ('30min', '30 minutos antes'), ('1hour', '1 hora antes'), ('1day', '1 día antes')], default='15min', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviado'), ('completed', 'Completado'), ('cancelled', 'Cancelado'), ('failed', 'Fallido')], default='pending', max_length=10)),
                ('send_attempts', models.PositiveIntegerField(default=0)),
                ('last_attempt', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('ai_subject', models.CharField(blank=True, max_length=200)),
                ('ai_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_send_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheduled_send_time'],
            },
        ),
        migrations.CreateModel(
            name='ReminderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminders_enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('calendar_enabled', models.BooleanField(default=True)),
                ('preferred_type', models.CharField(choices=[('email', 'Solo Email'), ('calendar', 'Solo Calendario'), ('both', 'Email y Calendario')], default='both', max_length=10)),
                ('current_frequency', models.CharField(choices=[('low', 'Baja (1 recordatorio)'), ('normal', 'Normal (2 recordatorios)'), ('high', 'Alta (3 recordatorios)')], default='normal', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_config', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=50)),
                ('details', models.TextField(blank=True)),
                ('success', models.BooleanField(default=True)),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='reminders.reminder')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['status', 'scheduled_send_time'], name='reminders_r_status_615559_idx'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['user', 'status'], name='reminders_r_user_id_8beec6_idx'),
        ),
    ]
