# Generated by Django 5.2.1 on 2025-06-15 20:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('target_datetime', models.DateTimeField(verbose_name='Fecha y hora objetivo')),
                ('reminder_type', models.CharField(choices=[('email', 'Solo Email'), ('calendar', 'Solo Google Calendar'), ('both', 'Email + Google Calendar')], default='both', max_length=20, verbose_name='Tipo de recordatorio')),
                ('timing', models.CharField(choices=[('immediate', 'Inmediato'), ('15_min', '15 minutos antes'), ('1_hour', '1 hora antes'), ('2_hours', '2 horas antes'), ('1_day', '1 día antes'), ('3_days', '3 días antes')], default='1_hour', max_length=20, verbose_name='Tiempo de anticipación')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviado'), ('completed', 'Completado'), ('cancelled', 'Cancelado'), ('failed', 'Fallido')], default='pending', max_length=20, verbose_name='Estado')),
                ('scheduled_send_time', models.DateTimeField(verbose_name='Programado para')),
                ('actual_send_time', models.DateTimeField(blank=True, null=True)),
                ('responded', models.BooleanField(default=False)),
                ('response_time', models.DateTimeField(blank=True, null=True)),
                ('response_action', models.CharField(blank=True, max_length=50)),
                ('email_message_id', models.CharField(blank=True, max_length=255)),
                ('calendar_event_id', models.CharField(blank=True, max_length=255)),
                ('send_attempts', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('ai_subject', models.CharField(blank=True, max_length=200, verbose_name='Asunto generado por IA')),
                ('ai_description', models.TextField(blank=True, verbose_name='Descripción generada por IA')),
                ('ai_priority', models.CharField(default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recordatorio',
                'verbose_name_plural': 'Recordatorios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReminderConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminders_enabled', models.BooleanField(default=True, verbose_name='Recordatorios activos')),
                ('preferred_type', models.CharField(choices=[('email', 'Solo Email'), ('calendar', 'Solo Google Calendar'), ('both', 'Email + Google Calendar')], default='both', max_length=20, verbose_name='Tipo preferido')),
                ('default_timing', models.CharField(choices=[('immediate', 'Inmediato'), ('15_min', '15 minutos antes'), ('1_hour', '1 hora antes'), ('2_hours', '2 horas antes'), ('1_day', '1 día antes'), ('3_days', '3 días antes')], default='1_hour', max_length=20, verbose_name='Tiempo de anticipación')),
                ('adaptive_frequency', models.BooleanField(default=True, verbose_name='Frecuencia adaptativa')),
                ('current_frequency', models.CharField(choices=[('high', 'Alta (frecuencia normal)'), ('medium', 'Media (frecuencia reducida)'), ('low', 'Baja (frecuencia mínima)'), ('disabled', 'Deshabilitado')], default='high', max_length=20)),
                ('consecutive_ignored', models.IntegerField(default=0)),
                ('last_adaptation', models.DateTimeField(blank=True, null=True)),
                ('email_enabled', models.BooleanField(default=True, verbose_name='Emails activos')),
                ('calendar_enabled', models.BooleanField(default=True, verbose_name='Google Calendar activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Recordatorio',
                'verbose_name_plural': 'Configuraciones de Recordatorios',
            },
        ),
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('details', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('reminder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='reminders.reminder')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Recordatorio',
                'verbose_name_plural': 'Logs de Recordatorios',
                'ordering': ['-timestamp'],
            },
        ),
    ]
