# Generated by Django 5.2.1 on 2025-06-22 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminders_enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('calendar_enabled', models.BooleanField(default=True)),
                ('preferred_type', models.CharField(choices=[('email', 'Solo Email'), ('calendar', 'Solo Calendario'), ('both', 'Email y Calendario')], default='both', max_length=10)),
                ('current_frequency', models.CharField(choices=[('low', 'Baja (1 recordatorio)'), ('normal', 'Normal (2 recordatorios)'), ('high', 'Alta (3 recordatorios)')], default='normal', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='reminderconfiguration',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='reminder',
            options={'ordering': ['scheduled_send_time']},
        ),
        migrations.AlterModelOptions(
            name='reminderlog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='actual_send_time',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='ai_priority',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='calendar_event_id',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='email_message_id',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='responded',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='response_action',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='response_time',
        ),
        migrations.RemoveField(
            model_name='reminderlog',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='reminderlog',
            name='user',
        ),
        migrations.AddField(
            model_name='reminder',
            name='last_attempt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='ai_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='ai_subject',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='reminder_type',
            field=models.CharField(choices=[('email', 'Email'), ('calendar', 'Calendario'), ('both', 'Ambos')], default='email', max_length=10),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='scheduled_send_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='send_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviado'), ('completed', 'Completado'), ('cancelled', 'Cancelado'), ('failed', 'Fallido')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='target_datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='timing',
            field=models.CharField(choices=[('immediate', 'Inmediato'), ('5min', '5 minutos antes'), ('15min', '15 minutos antes'), ('30min', '30 minutos antes'), ('1hour', '1 hora antes'), ('1day', '1 día antes')], default='15min', max_length=10),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='reminderlog',
            name='reminder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='reminders.reminder'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['status', 'scheduled_send_time'], name='reminders_r_status_615559_idx'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['user', 'status'], name='reminders_r_user_id_8beec6_idx'),
        ),
        migrations.AddField(
            model_name='reminderconfig',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_config', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ReminderConfiguration',
        ),
    ]
