# Generated by Django 5.2.1 on 2025-06-26 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('estudio', 'Estudio'), ('descanso', 'Descanso')], default='estudio', max_length=10)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('duracion_min', models.IntegerField()),
                ('completado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del Evento')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('event_type', models.CharField(choices=[('tarea', 'Tarea/Estudio'), ('clase', 'Clase/Académico'), ('descanso', 'Descanso'), ('personal', 'Personal'), ('otro', 'Otro')], default='tarea', max_length=20, verbose_name='Tipo de Evento')),
                ('priority', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10, verbose_name='Prioridad')),
                ('category', models.CharField(choices=[('Matemáticas', 'Matemáticas'), ('Química', 'Química'), ('Historia', 'Historia'), ('Programación', 'Programación'), ('General', 'General')], default='General', max_length=50, verbose_name='Categoría')),
                ('start_time', models.DateTimeField(verbose_name='Hora de Inicio')),
                ('end_time', models.DateTimeField(verbose_name='Hora de Fin')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Completado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['start_time', 'priority'],
            },
        ),
    ]
