# Generated by Django 5.2.1 on 2025-06-17 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Matemáticas', 'Matemáticas'), ('Química', 'Química'), ('Historia', 'Historia'), ('Programación', 'Programación'), ('General', 'General')], default='General', max_length=50, verbose_name='Categoría'),
        ),
    ]
