# Generated by Django 5.2.1 on 2025-06-16 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloqueestudio',
            name='tipo',
            field=models.CharField(choices=[('estudio', 'Estudio'), ('descanso', 'Descanso')], default='estudio', max_length=10),
        ),
        migrations.AlterField(
            model_name='bloqueestudio',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
